export const mockRoles = [
	{ id: 1, name: 'Trưởng phòng', status: true, isManager: true },
	{ id: 2, name: 'Thực tập sinh', status: true, isManager: false },
	{ id: 3, name: 'Nhân viên', status: false, isManager: false },
	{ id: 4, name: 'Phó giám đốc', status: true, isManager: true },
];

export const mockDepartments = [
	{ id: 1, name: 'Phòng kinh doanh', code: '1abc' },
	{ id: 2, name: 'Phòng công nghệ', code: '2avc' },
	{ id: 3, name: 'Phòng sản xuất', code: '3adv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
	// { id: 4, name: 'Phòng tài chính', code: '4bcv' },
];
export const Units = [
	{ id: 1, name: 'Đơn vị 1' },
	{ id: 2, name: 'Đơn vị 2' },
	{ id: 3, name: 'Đơn vị 3' },
];

export const mockEmployeeList = [
	{
		id: 1,
		name: 'Harriett Butler',
		status: 'active',
		roleId: 1,
		avatar: 'https://randomuser.me/api/portraits/women/65.jpg',
		isSelected: true,
		departmentId: 1,
		unitId: 1,
	},
	{
		id: 2,
		name: 'Melania Antoshin',
		roleId: 1,
		status: 'active',
		avatar: 'https://randomuser.me/api/portraits/women/66.jpg',
		isSelected: true,
		departmentId: 1,
		unitId: 2,
	},
	{
		id: 3,
		name: 'Ky Kellaway',
		status: 'active',
		roleId: 2,
		avatar: 'https://randomuser.me/api/portraits/men/67.jpg',
		isSelected: true,
		departmentId: 2,
		unitId: 2,
	},
	{
		id: 4,
		name: 'Persis Canon',
		status: 'inactive',
		roleId: 4,
		avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
		isSelected: true,
		departmentId: 3,
		unitId: 3,
	},
	{
		id: 5,
		name: 'Avery Lopez',
		roleId: 3,
		status: 'active',
		avatar: 'https://randomuser.me/api/portraits/men/69.jpg',
		isSelected: false,
		departmentId: null,
		unitId: 1,
	},
	{
		id: 6,
		name: 'Isabella Fox',
		roleId: 2,
		status: 'active',
		avatar: 'https://randomuser.me/api/portraits/women/70.jpg',
		isSelected: false,
		departmentId: null,
		unitId: 2,
	},
	{
		id: 7,
		name: 'Medlody Canon',
		status: 'inactive',
		roleId: 2,
		avatar: 'https://randomuser.me/api/portraits/women/25.jpg',
		isSelected: true,
		departmentId: 3,
		unitId: 3,
	},
];
